# fly.toml app configuration file generated for pirx-phonebook-backend on 2023-06-03T18:52:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pirx-phonebook-backend"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
